name: "Автотесты: Задача 2"

on:
  push:
    paths:
      - 'task2/**/*'

jobs:
  task2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Подготовка окружения (Docker BuildX)
      uses: docker/setup-buildx-action@v2.0.0
    - name: Сборка образа 
      run: docker build . -t task2
      working-directory: ./task2
    - name: Проверка рабочей директории
      run: bash .github/tests/test-workdir.sh /home/ilovedocker/app task2
    - name: Проверка энтрипоинта образа
      run: bash .github/tests/test-entrypoint.sh "[sh hello.sh]" task2
    - name: Проверка результата выполненения
      run: bash .github/tests/check-output.sh "task2" "Hello from Y.Practicum & Docker"